[package]
name = "audio_lib"
version = "0.1.0"
edition = "2024"

[dependencies]
audio_player = { path = "../audio_player" }
walkdir = "2.4"
symphonia = { version = "0.5", features = ["all"] }
rand = "0.9.1"
