[package]
name = "audio_arena"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["audio_lib", "audio_player"]

[dependencies]
audio_lib = { path = "./audio_lib" }
audio_player = { path = "./audio_player" }
